version: '3'

services:
  duckdns:
    container_name: duckdns-example
    image: davidlor/duckdns
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - duckdns.env
      - .duckdns.env
